# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69270765c2c778aac65292c061b0e55e34ec1d5f4c8350f2b4aafde56e57878c10a287a29beac6bd7d3e45fe0119555c81fa6129217ab18203095e0c4b37b819

test:
  secret_key_base: 52274db3dda92ad9aca36d74ce23b4ad6782e746083cecfaf9465234c79f7b74019a3e4aab15c682e752b72b643951732d5c7ec56c0b277fe154c5dfdcaa3a95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
